### PR TITLE
Adavin dev: 117_UMBS_FASET

### PR DESCRIPTION
**Pull request by annedavin**
I'm not too sure I did the unpublished citation correctly, but I made a note to revisit for ISCN 4 as it is a citation of unpublished field station data.

### CODE REVIEW

**Comment by annedavin** [comment]
This pull request now contains changes for 117 and 120.

**Comment by annedavin** [comment]
Also, I had two data citations for Harden in 2008 for the data_reports/120_USGS_Harden document, which I differentiated by using "a" and "b." I'm not sure this is the standard or appropriate convention to use in this instance.

**Comment by ktoddbrown** [comment]
> Also, I had two data citations for Harden in 2008 for the data_reports/120_USGS_Harden document, which I differentiated by using "a" and "b." I'm not sure this is the standard or appropriate convention to use in this instance.

Yes that was the right convention to use! Good guess!

**Review by ktoddbrown — APPROVED** [review]
Looks good!

**Pull request merged**
